stages:
  preprocess:
    cmd: python src_pretraitement.py
    deps:
    - src_pretraitement.py
    - tweets_suspect.csv
    outs:
    - tweets_suspect_clean.csv
  vectorization:
    cmd: python src_vectorisation.py
    deps:
    - src_vectorisation.py
    - tweets_suspect_clean.csv
    outs:
    - matrix_tfidf.pkl
    - tfidf_vectorizer.pkl
  build_models:
    cmd: python src_modeles.py
    deps:
    - src_modeles.py
    outs:
    - modeles_construits.pkl
